import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=120, unique=True, verbose_name="descripcion")),
            ],
            options={"verbose_name": "tipo de direccion", "verbose_name_plural": "tipos de direccion", "ordering": ["description"]},
        ),
        migrations.CreateModel(
            name="Birthplace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="nombre")),
                ("legacy_id", models.IntegerField(blank=True, null=True, verbose_name="id anterior")),
            ],
            options={"verbose_name": "lugar de nacimiento", "verbose_name_plural": "lugares de nacimiento", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Competency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=240, unique=True, verbose_name="descripcion")),
            ],
            options={"verbose_name": "competencia", "verbose_name_plural": "competencias", "ordering": ["description"]},
        ),
        migrations.CreateModel(
            name="ContactType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=120, unique=True, verbose_name="descripcion")),
            ],
            options={"verbose_name": "tipo de contacto", "verbose_name_plural": "tipos de contacto", "ordering": ["description"]},
        ),
        migrations.CreateModel(
            name="CurriculumInstitution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=160, unique=True, verbose_name="descripcion")),
                ("deleted", models.BooleanField(default=False, verbose_name="eliminado")),
            ],
            options={"verbose_name": "institucion de curriculum", "verbose_name_plural": "instituciones de curriculum", "ordering": ["description"]},
        ),
        migrations.CreateModel(
            name="CurriculumType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=160, unique=True, verbose_name="descripcion")),
            ],
            options={"verbose_name": "tipo de curriculum", "verbose_name_plural": "tipos de curriculum", "ordering": ["description"]},
        ),
        migrations.CreateModel(
            name="EmployeeType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="nombre")),
            ],
            options={"verbose_name": "tipo de empleado", "verbose_name_plural": "tipos de empleado", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="nombre")),
                ("legacy_id", models.IntegerField(blank=True, null=True, verbose_name="id anterior")),
            ],
            options={"verbose_name": "nacionalidad", "verbose_name_plural": "nacionalidades", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="PhoneType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=120, unique=True, verbose_name="descripcion")),
            ],
            options={"verbose_name": "tipo de telefono", "verbose_name_plural": "tipos de telefono", "ordering": ["description"]},
        ),
        migrations.AddField("course", "responsible", models.CharField(blank=True, max_length=160, verbose_name="responsable")),
        migrations.AddField("subject", "responsible", models.CharField(blank=True, max_length=160, verbose_name="responsable")),
        migrations.AddField("student", "gender", models.CharField(blank=True, max_length=20, verbose_name="sexo")),
        migrations.AddField("student", "photo_url", models.CharField(blank=True, max_length=300, verbose_name="url de foto")),
        migrations.AddField("student", "marital_status", models.CharField(blank=True, max_length=60, verbose_name="estado civil")),
        migrations.AddField("student", "license_number", models.CharField(blank=True, max_length=80, verbose_name="licencia")),
        migrations.RemoveField("student", "address"),
        migrations.AddField(
            "student",
            "birthplace",
            models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_people", to="core.birthplace", verbose_name="lugar de nacimiento"),
        ),
        migrations.AddField(
            "student",
            "nationality",
            models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_people", to="core.nationality", verbose_name="nacionalidad"),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120, verbose_name="nombres")),
                ("last_name", models.CharField(max_length=120, verbose_name="apellidos")),
                ("document_id", models.CharField(blank=True, max_length=20, verbose_name="cedula")),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="correo")),
                ("gender", models.CharField(blank=True, max_length=20, verbose_name="sexo")),
                ("photo_url", models.CharField(blank=True, max_length=300, verbose_name="url de foto")),
                ("marital_status", models.CharField(blank=True, max_length=60, verbose_name="estado civil")),
                ("license_number", models.CharField(blank=True, max_length=80, verbose_name="licencia")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="fecha de nacimiento")),
                ("birthplace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="teacher_people", to="core.birthplace", verbose_name="lugar de nacimiento")),
                ("nationality", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="teacher_people", to="core.nationality", verbose_name="nacionalidad")),
            ],
            options={"verbose_name": "docente", "verbose_name_plural": "docentes", "ordering": ["last_name", "first_name"]},
        ),
        migrations.CreateModel(
            name="EmployeePosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("employee_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="positions", to="core.employeetype", verbose_name="tipo de empleado")),
            ],
            options={"verbose_name": "posicion de empleado", "verbose_name_plural": "posiciones de empleados", "ordering": ["employee_type__name", "name"], "unique_together": {("employee_type", "name")}},
        ),
        migrations.CreateModel(
            name="AdministrativeEmployee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120, verbose_name="nombres")),
                ("last_name", models.CharField(max_length=120, verbose_name="apellidos")),
                ("document_id", models.CharField(blank=True, max_length=20, verbose_name="cedula")),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="correo")),
                ("gender", models.CharField(blank=True, max_length=20, verbose_name="sexo")),
                ("photo_url", models.CharField(blank=True, max_length=300, verbose_name="url de foto")),
                ("marital_status", models.CharField(blank=True, max_length=60, verbose_name="estado civil")),
                ("license_number", models.CharField(blank=True, max_length=80, verbose_name="licencia")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="fecha de nacimiento")),
                ("birthplace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="administrativeemployee_people", to="core.birthplace", verbose_name="lugar de nacimiento")),
                ("employee_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="administrative_employees", to="core.employeetype", verbose_name="tipo de empleado")),
                ("nationality", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="administrativeemployee_people", to="core.nationality", verbose_name="nacionalidad")),
                ("position", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="administrative_employees", to="core.employeeposition", verbose_name="posicion")),
            ],
            options={"verbose_name": "empleado administrativo", "verbose_name_plural": "empleados administrativos", "ordering": ["last_name", "first_name"]},
        ),
        migrations.CreateModel(
            name="SubjectCompetency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("competency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subject_competencies", to="core.competency")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subject_competencies", to="core.subject")),
            ],
            options={"verbose_name": "competencia por asignatura", "verbose_name_plural": "competencias por asignatura", "ordering": ["subject__name", "competency__description"], "unique_together": {("subject", "competency")}},
        ),
        migrations.AddField(
            "grade",
            "subject_competency",
            models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="grades", to="core.subjectcompetency", verbose_name="competencia"),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("street", models.CharField(max_length=180, verbose_name="calle")),
                ("number", models.CharField(max_length=40, verbose_name="numero")),
                ("apartment", models.CharField(blank=True, max_length=60, verbose_name="apartamento")),
                ("longitude", models.CharField(blank=True, max_length=80, verbose_name="longitud")),
                ("latitude", models.CharField(blank=True, max_length=80, verbose_name="latitud")),
                ("address_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="addresses", to="core.addresstype", verbose_name="tipo")),
                ("administrative_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="core.administrativeemployee", verbose_name="empleado administrativo")),
                ("city", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="addresses", to="core.city")),
                ("province", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="addresses", to="core.province")),
                ("sector", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="addresses", to="core.sector")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="core.student", verbose_name="estudiante")),
                ("teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="core.teacher", verbose_name="docente")),
            ],
            options={"verbose_name": "direccion", "verbose_name_plural": "direcciones", "ordering": ["street", "number"]},
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120, verbose_name="nombre")),
                ("last_name", models.CharField(max_length=120, verbose_name="apellido")),
                ("phone", models.CharField(max_length=40, verbose_name="telefono")),
                ("address", models.CharField(blank=True, max_length=240, verbose_name="direccion")),
                ("contact_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contacts", to="core.contacttype", verbose_name="tipo")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="core.student")),
                ("teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="core.teacher")),
            ],
            options={"verbose_name": "contacto", "verbose_name_plural": "contactos", "ordering": ["last_name", "first_name"]},
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40, verbose_name="numero")),
                ("administrative_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="phones", to="core.administrativeemployee")),
                ("phone_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="phones", to="core.phonetype")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="phones", to="core.student")),
                ("teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="phones", to="core.teacher")),
            ],
            options={"verbose_name": "telefono", "verbose_name_plural": "telefonos", "ordering": ["number"]},
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("folder", models.CharField(blank=True, max_length=240, verbose_name="carpeta")),
                ("administrative_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="curricula", to="core.administrativeemployee")),
                ("teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="curricula", to="core.teacher")),
            ],
            options={"verbose_name": "curriculum", "verbose_name_plural": "curricula"},
        ),
        migrations.CreateModel(
            name="CurriculumDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=240, verbose_name="descripcion")),
                ("date", models.DateField(blank=True, null=True, verbose_name="fecha")),
                ("file_url", models.CharField(blank=True, max_length=300, verbose_name="archivo")),
                ("deleted", models.BooleanField(default=False, verbose_name="eliminado")),
                ("curriculum", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="details", to="core.curriculum")),
                ("curriculum_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="curriculum_details", to="core.curriculumtype")),
                ("institution", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="curriculum_details", to="core.curriculuminstitution")),
            ],
            options={"verbose_name": "detalle de curriculum", "verbose_name_plural": "detalles de curriculum", "ordering": ["-date", "description"]},
        ),
    ]
