# Generated by Django 5.2.16 on 2026-07-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_person_photo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=60, unique=True, verbose_name='numero')),
                ('date', models.DateField(verbose_name='fecha')),
                ('payee', models.CharField(max_length=180, verbose_name='beneficiario')),
                ('concept', models.CharField(max_length=240, verbose_name='concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado'), ('cleared', 'Cobrado'), ('void', 'Anulado')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'cheque',
                'verbose_name_plural': 'cheques',
                'ordering': ['-date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='nombre')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='categoria')),
                ('unit', models.CharField(default='unidad', max_length=40, verbose_name='unidad')),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='existencia')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='minimo')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'material gastable',
                'verbose_name_plural': 'materiales gastables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'categoria de equipo',
                'verbose_name_plural': 'categorias de equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='fecha')),
                ('category', models.CharField(max_length=120, verbose_name='categoria')),
                ('description', models.CharField(max_length=240, verbose_name='descripcion')),
                ('vendor', models.CharField(blank=True, max_length=160, verbose_name='proveedor')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('cheque', 'Cheque')], default='cash', max_length=20, verbose_name='forma de pago')),
                ('cheque_number', models.CharField(blank=True, max_length=60, verbose_name='numero de cheque')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('date', models.DateField(verbose_name='fecha')),
                ('delivered_to', models.CharField(blank=True, max_length=160, verbose_name='entregado a')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.consumableitem', verbose_name='material')),
            ],
            options={
                'verbose_name': 'movimiento de material gastable',
                'verbose_name_plural': 'movimientos de material gastable',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='marca')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='numero de serie')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='ubicacion')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='fecha de adquisicion')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('loaned', 'Prestado'), ('maintenance', 'Mantenimiento'), ('retired', 'Retirado')], default='available', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.equipmentcategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_name', models.CharField(max_length=160, verbose_name='recibido por')),
                ('loan_date', models.DateField(verbose_name='fecha de prestamo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='fecha de devolucion esperada')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='fecha de devolucion')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido')], default='active', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_loans', to='core.administrativeemployee', verbose_name='empleado responsable')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.equipmentitem', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'prestamo de equipo',
                'verbose_name_plural': 'prestamos de equipos',
                'ordering': ['-loan_date', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(max_length=140, verbose_name='area')),
                ('role', models.CharField(max_length=160, verbose_name='funcion')),
                ('start_date', models.DateField(verbose_name='desde')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='hasta')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.administrativeemployee', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'asignacion de personal',
                'verbose_name_plural': 'asignaciones de personal',
                'ordering': ['employee__last_name', 'employee__first_name', 'area'],
            },
        ),
    ]
