# Generated by Django 5.2.16 on 2026-07-10 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cheque_consumableitem_equipmentcategory_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('bank_name', models.CharField(max_length=160, verbose_name='banco')),
                ('account_number', models.CharField(max_length=80, unique=True, verbose_name='numero de cuenta')),
                ('account_type', models.CharField(blank=True, max_length=80, verbose_name='tipo de cuenta')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['bank_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='fecha')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='referencia')),
                ('description', models.CharField(max_length=240, verbose_name='descripcion')),
                ('debit_account', models.CharField(max_length=160, verbose_name='cuenta debito')),
                ('credit_account', models.CharField(max_length=160, verbose_name='cuenta credito')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('related_cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.cheque', verbose_name='cheque relacionado')),
                ('related_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.expense', verbose_name='gasto relacionado')),
            ],
            options={
                'verbose_name': 'asiento de diario',
                'verbose_name_plural': 'asientos de diario',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='Ejemplo: 2025-09', max_length=20, verbose_name='periodo')),
                ('statement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo banco')),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo libro')),
                ('deposits_in_transit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='depositos en transito')),
                ('outstanding_checks', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cheques pendientes')),
                ('bank_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cargos bancarios')),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ajustes')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='core.bankaccount', verbose_name='cuenta bancaria')),
            ],
            options={
                'verbose_name': 'conciliacion bancaria',
                'verbose_name_plural': 'conciliaciones bancarias',
                'ordering': ['-period', 'bank_account__bank_name'],
                'unique_together': {('bank_account', 'period')},
            },
        ),
    ]
