# Generated by Django 5.2.16 on 2026-07-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_bankaccount_journalentry_bankreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(max_length=40, unique=True, verbose_name='numero de caso')),
                ('case_type', models.CharField(choices=[('incident', 'Incidencia'), ('support', 'Caso de apoyo'), ('referral', 'Referimiento'), ('family', 'Situacion familiar')], default='incident', max_length=20, verbose_name='tipo')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En seguimiento'), ('referred', 'Referido'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='estado')),
                ('opened_at', models.DateField(verbose_name='fecha de apertura')),
                ('reported_by', models.CharField(blank=True, max_length=160, verbose_name='reportado por')),
                ('summary', models.TextField(verbose_name='descripcion del caso')),
                ('initial_actions', models.TextField(blank=True, verbose_name='acciones iniciales')),
                ('confidential', models.BooleanField(default=True, verbose_name='confidencial')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('closing_notes', models.TextField(blank=True, verbose_name='notas de cierre')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guidance_cases', to='core.administrativeemployee', verbose_name='orientador o psicologo responsable')),
                ('referred_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_guidance_cases', to='core.teacher', verbose_name='docente que refiere')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guidance_cases', to='core.student', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'caso de orientacion',
                'verbose_name_plural': 'casos de orientacion',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='fecha')),
                ('intervention_type', models.CharField(choices=[('interview', 'Entrevista'), ('call', 'Llamada'), ('meeting', 'Reunion'), ('home_visit', 'Visita domiciliaria'), ('referral', 'Referimiento'), ('observation', 'Observacion')], max_length=20, verbose_name='tipo de seguimiento')),
                ('participants', models.CharField(blank=True, max_length=240, verbose_name='participantes')),
                ('notes', models.TextField(verbose_name='notas')),
                ('next_steps', models.TextField(blank=True, verbose_name='proximos pasos')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='proxima fecha')),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_followups', to='core.administrativeemployee', verbose_name='atendido por')),
                ('guidance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.guidancecase', verbose_name='caso')),
            ],
            options={
                'verbose_name': 'seguimiento de orientacion',
                'verbose_name_plural': 'seguimientos de orientacion',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
