# Generated by Django 5.2.16 on 2026-07-15 12:16

from django.db import migrations, models


def move_referred_cases_to_in_progress(apps, schema_editor):
    GuidanceCase = apps.get_model("core", "GuidanceCase")
    GuidanceCase.objects.filter(status="referred").update(status="in_progress")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_guidancecase_guidancefollowup'),
    ]

    operations = [
        migrations.RunPython(move_referred_cases_to_in_progress, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='guidancecase',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En proceso'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='estado'),
        ),
    ]
