# Generated by Django 5.2.16 on 2026-07-15 12:28

import django.db.models.deletion
from django.db import migrations, models


def clear_legacy_guidance_responsibles(apps, schema_editor):
    GuidanceCase = apps.get_model("core", "GuidanceCase")
    GuidanceFollowUp = apps.get_model("core", "GuidanceFollowUp")
    GuidanceCase.objects.update(assigned_to=None)
    GuidanceFollowUp.objects.update(attended_by=None)


def assign_three_guidance_counselors(apps, schema_editor):
    Teacher = apps.get_model("core", "Teacher")
    teacher_ids = list(Teacher.objects.filter(active=True).order_by("?").values_list("id", flat=True)[:3])
    if teacher_ids:
        Teacher.objects.filter(id__in=teacher_ids).update(is_guidance_counselor=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_guidancecase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_guidance_counselor',
            field=models.BooleanField(default=False, verbose_name='es orientador/psicologo'),
        ),
        migrations.RunPython(clear_legacy_guidance_responsibles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='guidancecase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guidance_cases', to='core.teacher', verbose_name='orientador o psicologo responsable'),
        ),
        migrations.AlterField(
            model_name='guidancefollowup',
            name='attended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_followups', to='core.teacher', verbose_name='atendido por'),
        ),
        migrations.RunPython(assign_three_guidance_counselors, migrations.RunPython.noop),
    ]
