# Generated by Django 5.2.16 on 2026-07-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_teacher_is_guidance_counselor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidancecase',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_cases', to='core.student', verbose_name='estudiante'),
        ),
    ]
