# Generated by Django 5.2.16 on 2026-07-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_guidancecase_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancecase',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guidance_cases', to='core.section', verbose_name='grado o seccion'),
        ),
    ]
