# Generated by Django 5.2.16 on 2026-07-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_guidancecase_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancefollowup',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='guidance/evidence/', verbose_name='evidencia'),
        ),
    ]
