# Generated by Django 5.2.17 on 2026-09-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_systemconfiguration_current_school_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrule',
            options={'permissions': [('manage_users_roles', 'Puede gestionar usuarios y roles'), ('manage_people', 'Puede gestionar estudiantes, docentes y personal'), ('manage_academic_setup', 'Puede gestionar cursos, secciones, asignaturas y docencia'), ('view_all_academic', 'Puede ver todas las secciones y calificaciones'), ('view_own_sections', 'Puede ver sus secciones asignadas'), ('edit_grades', 'Puede editar calificaciones'), ('import_grades', 'Puede importar calificaciones desde Excel'), ('view_grade_stats', 'Puede ver estadisticas de calificaciones'), ('view_all_school_years', 'Puede ver informacion de todos los anos escolares')], 'verbose_name': 'regla de acceso', 'verbose_name_plural': 'reglas de acceso'},
        ),
    ]
