# Generated by Django 5.2.17 on 2026-09-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_accessrule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['nationality__name', 'name'], 'verbose_name': 'provincia o estado', 'verbose_name_plural': 'provincias o estados'},
        ),
        migrations.AddField(
            model_name='province',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='core.nationality', verbose_name='nacionalidad'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('nationality', 'name')},
        ),
    ]
