# Generated by Django 6.1 on 2026-08-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('laboratorio', 'Laboratorio'), ('auditorio', 'Auditorio')], default='normal', max_length=20, verbose_name='tipo')),
                ('capacidad', models.PositiveIntegerField(verbose_name='capacidad')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('grado', models.CharField(max_length=20, verbose_name='grado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('horas_semanales_requeridas', models.PositiveSmallIntegerField(verbose_name='horas semanales requeridas')),
                ('franja_preferente', models.CharField(blank=True, help_text='mañana, tarde, mixto', max_length=20, verbose_name='franja horaria preferente')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RestriccionPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_libre', models.TextField(verbose_name='texto libre')),
                ('regla_json', models.JSONField(blank=True, default=dict, verbose_name='regla JSON')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('procesada', models.BooleanField(default=False, verbose_name='procesada')),
            ],
            options={
                'verbose_name': 'restriccion personalizada',
                'verbose_name_plural': 'restricciones personalizadas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIÉ', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], max_length=10, verbose_name='dia')),
                ('hora_inicio', models.TimeField(verbose_name='hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora fin')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='orden dentro del dia')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bloque horario',
                'verbose_name_plural': 'bloques horario',
                'ordering': ['dia', 'orden'],
                'unique_together': {('dia', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionMateriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_asignadas', models.PositiveSmallIntegerField(verbose_name='horas asignadas')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_materia', to='timetabling.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetabling.materia')),
            ],
            options={
                'verbose_name': 'asignacion materia-grupo',
                'verbose_name_plural': 'asignaciones materia-grupo',
                'unique_together': {('materia', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='materias',
            field=models.ManyToManyField(through='timetabling.AsignacionMateriaGrupo', to='timetabling.materia', verbose_name='materias'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('disponibilidad', models.JSONField(blank=True, default=dict, help_text='{"LUN": [0, 1, 2], "MAR": [3, 4]} — lista de indices de bloques disponibles por dia', verbose_name='disponibilidad')),
                ('horas_max_dia', models.PositiveSmallIntegerField(default=6, verbose_name='horas maximas por dia')),
                ('horas_max_semana', models.PositiveSmallIntegerField(default=24, verbose_name='horas maximas por semana')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materias_habilitadas', models.ManyToManyField(blank=True, related_name='profesores_habilitados', to='timetabling.materia', verbose_name='materias habilitadas')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='timetabling.aula')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='timetabling.bloquehorario')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='timetabling.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='timetabling.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='timetabling.profesor')),
            ],
            options={
                'verbose_name': 'asignacion horario',
                'verbose_name_plural': 'asignaciones horario',
                'ordering': ['bloque__dia', 'bloque__orden'],
                'indexes': [models.Index(fields=['profesor', 'bloque'], name='timetabling_profeso_3557d8_idx'), models.Index(fields=['grupo', 'bloque'], name='timetabling_grupo_i_84d4a9_idx'), models.Index(fields=['aula', 'bloque'], name='timetabling_aula_id_cdc1bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('profesor', 'bloque'), name='unique_profesor_bloque'), models.UniqueConstraint(fields=('grupo', 'bloque'), name='unique_grupo_bloque'), models.UniqueConstraint(fields=('aula', 'bloque'), name='unique_aula_bloque')],
            },
        ),
    ]
