# Generated by Django 5.2.17 on 2026-09-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0002_horariojob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariojob',
            options={'ordering': ['-creado_en'], 'verbose_name': 'horario job', 'verbose_name_plural': 'horarios jobs'},
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='asignaciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='datos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='estadisticas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='job_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='mensaje',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='progreso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='horariojob',
            name='restricciones_relajadas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
